name: BlockPalletGUI
version: '1.0'
main: org.example.bte.blockPalletGUI.Main
api-version: '1.20'
commands:
  blockpallet:
    description: Opens the block pallet GUI.
    usage: /blockpallet menu, /blockpallet color, /blockpallet slabs, /blockpallet stairs, /blockpallet walls, /blockpallet logs, /blockpallet leaves, /blockpallet fences, /blockpallet glass, /blockpallet carpet, /blockpallet wool, /blockpallet terracotta, /blockpallet concrete, /blockpallet concrete_powder, /blockpallet bed, /blockpallet candle, /blockpallet banner, /blockpallet glass_pane, /blockpallet signs, /blockpallet shulker_boxes, /blockpallet gates
    permission: blockpallet.use
permissions:
  blockpallet.use:
    description: Allows the player to use the blockpallet command.
    default: true