name: BlockPalletGUI
version: '1.0'
main: org.example.bte.blockPalletGUI.Main
api-version: '1.20'
commands:
  blockpallet:
    description: Opens the block pallet GUI.
    usage: /blockpallet color, /blockpallet slabs, /blockpallet stairs, /blockpallet walls, /blockpallet logs, /blockpallet leaves, /blockpallet fences, /blockpallet glass, /blockpallet carpet, /blockpallet wool, /blockpallet terracotta, /blockpallet concrete, or /blockpallet concrete_powder
    permission: blockpallet.use
permissions:
  blockpallet.use:
    description: Allows the player to use the blockpallet command.
    default: true